name: Rust

on:
  push:
    branches: master
  pull_request:
    paths-ignore:
      - '**.md'

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --verbose
    - name: Lint
      run: cargo clippy -- -D warnings
    - name: Format Check
      run: cargo fmt -- --check
    - name: Run tests
      run: cargo test --verbose
